from typing import List

import numpy as np

from sdl.lab import Operation


class OperationFactory:
    '''Factory class for creating Operation objects
    Each operation has an operation id, operation name and duration
    The operation names are generated by ChatGPT. The duration is randomly generated.
    '''
    def __init__(self):
        self.rs = np.random.RandomState(42)
        self.operations = []

    def create_operation(self, operation_id: int, operation_name: str, duration: int) -> Operation:
        return Operation(operation_id, operation_name, duration)

    def create_operation_set(self, filename='operations.txt') -> List[Operation]:
        try:
            with open(filename, 'r') as f:
                operations = f.readlines()
            # operations = [op.strip() for op in operations]
        except IOError as e:
            print(f'Cannot open file {filename}')
            print(e)
            return []
        self.operations = []
        for id, name in enumerate(operations):
            duration = self.rs.randint(5, 50)
            self.operations.append(self.create_operation(id+1, name.strip(), duration))
            # print(self.operations)
        return self.operations
        # return [self.create_operation(op_id, op_name) for op_id, op_name in operation_set]

    def choose_n_operations(self, n: int) -> List[Operation]:
        return self.rs.choice(self.operations, n, replace=False)
